/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function scrapeWebsite(startUrl: string): Array<string>
export declare function scrapeTextFromUrls(urls: Array<string>): Promise<Array<string>>
export const enum ModelTypes {
  AllMiniLML6V2 = 0,
  BGESmallENV15 = 1,
  MultilingualE5Large = 2,
  AllMiniLML12V2 = 3,
  AllMiniLML6V2Q = 4,
  BGELargeENV15Q = 5,
  NomicEmbedTextV15 = 6,
  BGEBaseENV15 = 7,
  NomicEmbedTextV1 = 8,
  BGEBaseENV15Q = 9,
  ParaphraseMLMiniLML12V2 = 10,
  ParaphraseMLMpnetBaseV2 = 11,
  MultilingualE5Small = 12,
  GTEBaseENV15 = 13,
  GTELargeENV15 = 14,
  MxbaiEmbedLargeV1 = 15,
  MultilingualE5Base = 16,
  ParaphraseMLMiniLML12V2Q = 17,
  BGESmallENV15Q = 18,
  BGESmallZHV15 = 19,
  MxbaiEmbedLargeV1Q = 20,
  NomicEmbedTextV15Q = 21,
  GTEBaseENV15Q = 22,
  AllMiniLML12V2Q = 23,
  GTELargeENV15Q = 24,
  BGELargeENV15 = 25
}
export declare function generateEmbeddings(documents: Array<string>, modelName: ModelTypes): Array<Array<number>>
